AWSTemplateFormatVersion: 2010-09-09
Description: >-
            Someone is squatting on your domain name! Or are they?
            We'll never know... unless we check. And that's why ***great squat*** is here.
            Give us a domain name, and we'll check to see what squatters might be out there.
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is an API gateway associated with the getByIdFunction and putItemFunctions
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, POST, GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'" 

## Entry into the system from the web
#  Receives ScanRequests from the web, 
#  records them to db and the ScanRequestsQueue
  ScanRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./serverless/backend/
      Handler: src/handlers/scan-request.scanRequestHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description:
        Receives ScanRequests from the web, and deposits them into a queue and a record in the db
      Policies:
        # Give Create/Read/Update/Delete Permissions to the RequestTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RequestTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ScanRequestsQueue.QueueName      
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref RequestTable
          SQS_QUEUE_URL: !GetAtt ScanRequestsQueue.QueueUrl
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  GetAllRequests:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./serverless/backend/
      Handler: src/handlers/get-all-requests.getAllRequestsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 5
      Description:
        Get all requests from the requests table for use in the web UI
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RequestTable
      Environment:
        Variables:
          REQUEST_TABLE: !Ref RequestTable
      Events:
        Api:
          Type: Api 
          Properties:
            Path: /requests
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi


  DomainPermutationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Is triggered by the ScanRequestsQueue and produces permutations of the domain name into the DomainPermutationsQueue
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt DnsResolverQueue.QueueUrl
      CodeUri: ./serverless/backend/
      Handler: src/handlers/domain-permutation.handler
      Runtime: nodejs18.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ScanRequestsQueue.Arn
            BatchSize: 1
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DomainPermutationsQueue.QueueName

  # works the incoming queue of scan requests to produce
  # permutations of the domain name into the next queue
  DnsResolverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./serverless/backend/
      Handler: src/handlers/resolve-domain.handler
      Runtime: nodejs18.x
      Description: Is triggered by the DomainPermutationsQueue and resolves the domain name into the the DB
      Environment:
        Variables:
          RESOLVER_TABLE: !Ref ResolutionTable
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt DomainPermutationsQueue.Arn
            BatchSize: 1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResolutionTable


  # Holds incoming scan requests until they can be processed
  # for permutations or scanned directly
  ScanRequestsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-scan-requests"
      MessageRetentionPeriod: 172800
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  #  holds all permutations of domains that might exist
  # in preparation for them to be scanned
  DomainPermutationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-domain-permutations"
      MessageRetentionPeriod: 172800
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  # Holds domains that we want to scan and feeds a function that will
  # check resolution and record results.
  DnsResolverQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-dns-resolver"
      MessageRetentionPeriod: 172800
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3


  # lost messages flow here
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-dead-letter"
      MessageRetentionPeriod: 1209600

  RequestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

      AttributeDefinitions:
        - AttributeName: "domain"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "domain"
          KeyType: "HASH"
        - AttributeName: "date"
          KeyType: "RANGE"
      Tags:
        - Key: foo
          Value: bar

  ResolutionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

      AttributeDefinitions:
        - AttributeName: "domain"
          AttributeType: "S"
        - AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "domain"
          KeyType: "HASH"
        - AttributeName: "date"
          KeyType: "RANGE"
      Tags:
        - Key: foo
          Value: bar

  # S3 Bucket to host single page app website
  WebSiteBucket:
    Type: AWS::S3::Bucket

  WebSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Join ["", ["arn:aws:s3:::", !Ref WebSiteBucket, /*]]
            Condition:
              StringEquals:
                AWS:SourceArn:
                  !Join [
                    "",
                    [
                      "arn:aws:cloudfront::",
                      !Ref "AWS::AccountId",
                      ":distribution/",
                      !Ref CloudFrontDistribution,
                    ],
                  ]
  
  # CloudFront Distribution for hosting the single page app website
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebSiteBucket.RegionalDomainName
            Id: myS3Origin
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
        PriceClass: PriceClass_200
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - US
              - CA
              - GB
              - DE
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${WebSiteBucket} OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Outputs:
  # APIGatewayEndpoint:
  #   Description: API Gateway endpoint URL for Prod stage
  #   Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID for hosting web front end
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name for accessing web front end
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebS3BucketName:
    Description: S3 Bucket for hosting web frontend
    Value: !Ref WebSiteBucket
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"